version: "3.3"
services:
  client:
    ports:
      - "80:80"
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - API_URL=http://137:184:155:95/api
    restart: on-failure
    container_name: client