import axios from 'axios';

export const BASE_URL = 'https://shift2gotest.herokuapp.com/api/v1';

const API = () => {
  return axios.create({
    baseURL: BASE_URL,
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
      // 'Access-Control-Allow-Origin': '*',
    },
  });
};

export default API;

[
  {
    roles_ids: [],
    requiredCertificatesTypes: null,
    active: true,
    pay: 10,
    targetAudience: null,
    contractor_id: null,
    startTime: '2021-11-13T04:53:00',
    audienceType: 'MARKET',
    createdBy: 58,
    endTime: '2021-11-13T04:53:00',
    clockInLatitude: null,
    createdAt: '2021-11-11T10:32:49.892109',
    startedAt: null,
    clockOutLatitude: null,
    updatedAt: null,
    id: 44,
    endedAt: null,
    clockInLongitude: null,
    name: 'name',
    instructions: 'sadfdadaa',
    clockOutLongitude: null,
    hotel_id: 4,
    status: 'PENDING',
    contractor: null,
    hotel: {
      employerIdentificationNumber: '033333',
      notification: {
        email: true,
        push: true,
      },
      bank_id: 16,
      rating: null,
      id: 4,
      pictures: null,
      createdAt: '2021-11-08T11:41:24.609036',
      createdBy: 58,
      favouriteContractors: null,
      updatedAt: null,
      hotelAdmin: 4,
      contractorsRadius: 20,
      name: 'Dollar Mansion',
      latitude: -0.452,
      address: 'Abuja',
      longitude: -6.569,
      phone: '1234567890',
    },
    manager: {
      profilePicture: 'fine_boy',
      id: 4,
      verified: false,
      updatedAt: null,
      userID: 58,
      rating: null,
      createdAt: '2021-11-02T13:01:25.424759',
    },
    roles: [],
    certificates_types: [],
    requests: [],
    owner: {
      email: 'saidinusah29@gmail.com',
      address: '44 bull stree',
      is_verified: true,
      countryCode: null,
      is_active: true,
      phone: '553208841',
      latitude: null,
      id: 58,
      longitude: null,
      createdAt: '2021-11-02T13:01:25.382408',
      firstname: 'Said',
      userType: 'MANAGER',
      updatedAt: '2021-11-06T08:54:26.740498',
      lastname: 'Inusah',
    },
  },
  {
    roles_ids: [6],
    requiredCertificatesTypes: null,
    active: true,
    pay: 35,
    targetAudience: null,
    contractor_id: null,
    startTime: '2021-11-08T13:41:14.537000',
    audienceType: 'MARKET',
    createdBy: 58,
    endTime: '2021-11-08T11:41:14.537000',
    clockInLatitude: null,
    createdAt: '2021-11-08T11:18:16.165690',
    startedAt: null,
    clockOutLatitude: null,
    updatedAt: null,
    id: 41,
    endedAt: null,
    clockInLongitude: null,
    name: 'Food Handling',
    instructions: 'make sure you sleep enough and get the job done please',
    clockOutLongitude: null,
    hotel_id: 4,
    status: 'PENDING',
    contractor: null,
    hotel: {
      employerIdentificationNumber: '033333',
      notification: {
        email: true,
        push: true,
      },
      bank_id: 16,
      rating: null,
      id: 4,
      pictures: null,
      createdAt: '2021-11-08T11:41:24.609036',
      createdBy: 58,
      favouriteContractors: null,
      updatedAt: null,
      hotelAdmin: 4,
      contractorsRadius: 20,
      name: 'Dollar Mansion',
      latitude: -0.452,
      address: 'Abuja',
      longitude: -6.569,
      phone: '1234567890',
    },
    manager: {
      profilePicture: 'fine_boy',
      id: 4,
      verified: false,
      updatedAt: null,
      userID: 58,
      rating: null,
      createdAt: '2021-11-02T13:01:25.424759',
    },
    roles: [
      {
        name: 'Food handling',
        createdBy: 1,
        updatedAt: null,
        image:
          'https://firebasestorage.googleapis.com/v0/b/shift2go-app.appspot.com/o/job_roles%2Ffood_handling.png?alt=media&token=e0a60b75-e82a-458b-a1ab-f9999da3c842',
        createdAt: '2021-10-15T06:24:37.223980',
        id: 6,
      },
    ],
    certificates_types: [],
    requests: [],
    owner: {
      email: 'saidinusah29@gmail.com',
      address: '44 bull stree',
      is_verified: true,
      countryCode: null,
      is_active: true,
      phone: '553208841',
      latitude: null,
      id: 58,
      longitude: null,
      createdAt: '2021-11-02T13:01:25.382408',
      firstname: 'Said',
      userType: 'MANAGER',
      updatedAt: '2021-11-06T08:54:26.740498',
      lastname: 'Inusah',
    },
  },
  {
    roles_ids: [],
    requiredCertificatesTypes: null,
    active: true,
    pay: 50,
    targetAudience: null,
    contractor_id: null,
    startTime: '2021-11-11T18:24:00',
    audienceType: 'MARKET',
    createdBy: 58,
    endTime: '2021-11-11T19:24:00',
    clockInLatitude: null,
    createdAt: '2021-11-11T19:24:04.661132',
    startedAt: null,
    clockOutLatitude: null,
    updatedAt: null,
    id: 45,
    endedAt: null,
    clockInLongitude: null,
    name: 'name',
    instructions: 'please wear nose masks when you come in',
    clockOutLongitude: null,
    hotel_id: 4,
    status: 'PENDING',
    contractor: null,
    hotel: {
      employerIdentificationNumber: '033333',
      notification: {
        email: true,
        push: true,
      },
      bank_id: 16,
      rating: null,
      id: 4,
      pictures: null,
      createdAt: '2021-11-08T11:41:24.609036',
      createdBy: 58,
      favouriteContractors: null,
      updatedAt: null,
      hotelAdmin: 4,
      contractorsRadius: 20,
      name: 'Dollar Mansion',
      latitude: -0.452,
      address: 'Abuja',
      longitude: -6.569,
      phone: '1234567890',
    },
    manager: {
      profilePicture: 'fine_boy',
      id: 4,
      verified: false,
      updatedAt: null,
      userID: 58,
      rating: null,
      createdAt: '2021-11-02T13:01:25.424759',
    },
    roles: [],
    certificates_types: [],
    requests: [],
    owner: {
      email: 'saidinusah29@gmail.com',
      address: '44 bull stree',
      is_verified: true,
      countryCode: null,
      is_active: true,
      phone: '553208841',
      latitude: null,
      id: 58,
      longitude: null,
      createdAt: '2021-11-02T13:01:25.382408',
      firstname: 'Said',
      userType: 'MANAGER',
      updatedAt: '2021-11-06T08:54:26.740498',
      lastname: 'Inusah',
    },
  },
];