# Your workflow name.
name: Deploy to AWS

# Run workflow on every push to prod main branch.
on:
  push:
    branches: [main, develop]
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# Your workflows jobs.
jobs:
  build:
    name: Build and Push to aws
    runs-on: ubuntu-latest
    steps:
      - name: Deploy package to aws
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.AWS_HOST}}
          username: ${{ secrets.AWS_USERNAME}}
          key: ${{ secrets.AWS_KEY }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            sudo su
            sudo apt-get upgrade -y
            cd
            cd /etc/shift2go/gitRepo/shift2goWeb
            sudo git checkout develop
            sudo git pull
            sudo docker image prune -f
            sudo docker container prune -f
            sudo docker volume prune -f
            sudo docker-compose -f aws-compose.yml up --force-recreate --build -d